version: '3.8'
services:
  database:
    container_name: transfers-db
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "5432:5432"
    networks:
      - transfers-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 10s
      retries: 5

  transfers-app:
    container_name: transfers-app
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#        - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/transfers
#        - SPRING_DATASOURCE_USERNAME=admin
#        - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - transfers-net
    depends_on:
      - database

networks:
  transfers-net:
    driver: bridge
